# Variables
$OutputContent = ""
$RootDir = Split-Path (Get-Location) -Parent
$ScriptsDir = Join-Path $RootDir "scripts"
$ModulesDir = Join-Path $RootDir "modules"
$OutputFile = Join-Path $RootDir "releases\winfix.ps1"
$Header = @"
################################################################################################################
###                                                                                                          ###
### WARNING: This file is automatically generated DO NOT modify this file directly as it will be overwritten ###
###                                                                                                          ###
################################################################################################################

# Parameters
param (
    [switch]`$IsModule = `$false,
    [switch]`$Silent = `$false
)

# Functions
"@

# Initial message
Clear-Host
Write-Host "Started process!" -ForegroundColor Cyan

# Remove previous file
if (Get-Item $OutputFile -ErrorAction SilentlyContinue) {
    Write-Host "Deleting previous file..."
    Remove-Item $OutputFile -Force
}

# Add header
Write-Host "Creating content with header..."
$OutputContent += $Header + "`n"
Write-Host ""

# Get all files in the modules folder
Write-Host "Joining all modules!" -ForegroundColor Cyan
Get-ChildItem -Path $ModulesDir -Filter *.psm1 | ForEach-Object {
    # Get the content of the file
    $Content = Get-Content $_.FullName
    $FilteredContent = $Content | Where-Object { $_ -notmatch "^Import-Module" -and $_ -notmatch "^#" }
    Write-Host "Getting contents of $_..."
    $OutputContent += ($FilteredContent -join "`n") + "`n"
}
Write-Host ""

# Get all files in the scripts folder
Write-Host "Joining all scripts!" -ForegroundColor Cyan
Get-ChildItem -Path $ScriptsDir -Filter *.ps1 | ForEach-Object {
    # Get the content of the file
    $Content = Get-Content $_.FullName
    $FilteredContent = $Content | Where-Object { $_ -notmatch "^Import-Module" -and $_ -notmatch "^#" }
    Write-Host "Getting contents of $_..."
    $OutputContent += ($FilteredContent -join "`n") + "`n"
}
Write-Host ""

# Get all files in the scripts folder
Write-Host "Joining all main files!" -ForegroundColor Cyan
Get-ChildItem -Path $RootDir -Filter *.ps1 | ForEach-Object {
    # Get the content of the file
    $Content = Get-Content $_.FullName
    $FilteredContent = $Content | Where-Object { $_ -notmatch "^Import-Module" -and $_ -notmatch "^#" }
    Write-Host "Getting contents of $_..."
    $OutputContent += ($FilteredContent -join "`n") + "`n"
}
Write-Host ""

# Save contents
Write-Host "Started to save content!" -ForegroundColor Cyan
Set-Content -Path $OutputFile -Value $OutputContent
Write-Host "Content has been saved in $OutputFile!" -ForegroundColor Green
Write-Host ""

# End script
Pause
Clear-Host
